### ISSUE TITLE
SPIKE: Find a front end framework for the website

### ISSUE THREAD

**Issue by JingusJohn** [CamJak/Boss-Integrated-Scheduler#3]
# Description

Research available options and decide which one best fits our project.

Angular
React
Svelte
Vue

# Acceptance Criteria

Decision is made on a framework to work with for the UI of the website.

**Comment by AGSAVALIYA** [comment]
I suggest you to use React

**Comment by jackjohn7** [comment]
While Svelte has a lot of awesome features that serve to make the development of components easier, SvelteKit as a framework is unfinished and things are subject to change before the 1.0 release. I'm reopening this item because SvelteKit doesn't seem to be the move for the project. Now thinking of going with Angular or React. Only problem with Angular is that it's a very bloated, large framework that leads to massive bundle size. Not super efficient for client side rendering

**Comment by jackjohn7** [comment]
Now that I've picked up some experience in SvelteKit and that SvellteKit has had a 1.0 release, I'm going to resume looking into whether or not it can meet our needs for this little project.
