### ISSUE TITLE
SPIKE: Research API Frameworks

### ISSUE THREAD

**Issue by JingusJohn** [CamJak/Boss-Integrated-Scheduler#6]
Whatever API framework we use just has to be written in a language that has some sort of database connectivity to whatever database we decide to use.

Python:
  FastAPI
JavaScript/Typescript:
  Express

You can also make API's with Go, Rust, and Java.

GraphQL is also super popular right now.

**Comment by jackjohn7** [comment]
After some research and consideration, I think we should go with Golang for the API backend. Go is a small bit less performant than Rust, but its ease of setup is definitely worth the trade off. It'll still be very fast. Here's a link to some API benchmarks. https://web-frameworks-benchmark.netlify.app/result

**Comment by jackjohn7** [comment]
Closing this for now. Our API layer is being build with NestJS for simplicity. NestJS is like the Angular of backends, but the problems that plague Angular aren't super relevant in the context of API development. NestJS is highly modular. Everything in NestJS is in a module. It has dependency injection just like Angular which is pretty handy. An example of this can be seen in the Auth Module of the API. You'll see it in constructors in various places in the codebase.

Since we're using something in javascript, we'll have access to some of the best libraries out there for interacting with a database and hashing. The thing we're currently using for password hashing Argon2 actually won a competition for the best hashing algorithm a few years ago.
